### ISSUE TITLE
FatalErrorException when not logged in

### ISSUE THREAD

**Issue by f0nt4** [Prophet731/BFAdminCP#156]
Hey man,

I noticed that when you're not logged in, the page displays an error (develop branch).
I tried redownloading all but to no luck.
http://puu.sh/mNdC3/45be890ebd.png
When you login, everything is fine.

Is there btw any way to run the dev-laravel5 branch?

Regards, Fonta

**Comment by Prophet731** [comment]
Don't use the develop branch. Use either the master branch or the v2.0.1.

As for the dev-laravel5 branch you can use it, however it's not stable and can break when I make changes. Plus, you can't run this on an existing database with a current install of the latest version. Since I'm going to be doing table changes for 1 or 2 of them.

**Comment by f0nt4** [comment]
I'm already using the develop branch since ages. You even configured the crontab to keep it up to date ;)

**Comment by Prophet731** [comment]
I fixed this error on the dev branch. Just noting that.

**Comment by f0nt4** [comment]
Thanks!
