### ISSUE TITLE
FEATURE_REQ: Database maintenance

### ISSUE THREAD

**Issue by killengage** [Prophet731/BFAdminCP#241]
@Prophet731 

Is it possible to add db maintenance to the new BFACP version ?  Possible examples:

- Backup DB
- Delete chatlog (older then 3, 6 12 months)
- When deleting servers option to clean up the DB (Yes/no)
- Delete player_records

**Comment by Prophet731** [comment]
> Backup DB

Backing up the database through PHP might not be the best option, especially when you have a very large database >= 1GB. The best solution would be to use a bash script which is located in the scripts folder under the BFACP. Located [here](https://github.com/Prophet731/BFAdminCP/blob/master/scripts/db-backup.sh).

> Delete chatlog (older then 3, 6 12 months)
> When deleting servers option to clean up the DB (Yes/no)
> Delete player_records

I'm hesitant to adding the ability to delete records from the web ui. Especially when you want one that can purge a server's entire data collection as if you didn't have a backup for some reason there will be no way to undo that action. Deleting information also defeats the purpose of what Colon and I built. That's why we both haven't added functionality for that.

**Comment by killengage** [comment]
This all makes sense Prophet, thanks for  the clarification.

Verstuurd vanaf mijn iPhone
