### ISSUE TITLE
Request: regex %player% search

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#67]
Hi

I'm not sure if this has already been requested, but I want to search for a player by just mentioning parts of his name, even if I take that part from the middle, without needing to use the % character.

Currently, if I use the % character, I get a 400 error code

**Comment by Prophet731** [comment]
The problem with this is preformance. When you use a % in front of of the name it needs to scan the entire table instead of using the index.

So a search like this would cause it to scan the entire table looking for a match where prop exists without using the index and this would need to happen each time.

```SQL
SELECT * FROM `tbl_playerdata` WHERE `SoldierName` LIKE '%prop%';
```

However a search like this allows the use of index for the player names and has faster performance. Although you would need to know the first few characters of a persons name.

This is how it's currently done and its the most efficient way.

```SQL
SELECT * FROM `tbl_playerdata` WHERE `SoldierName` LIKE 'prop%';
```

As you can see it takes longer with the first query compared to the second one. On a remote connection it can be longer.

![](http://i.gyazo.com/5f16c8b353026916e7609c646726c87c.png)

**Comment by iraqiboy90** [comment]
ok, I understand :+1:

**Comment by Prophet731** [comment]
I've updated the code to allow searches on a wildcard. You will need to prepend an asterisk (*) in front of the name to trigger it.

**Comment by iraqiboy90** [comment]
:+1:
