### ISSUE TITLE
Filter server name doesn't work

### ISSUE THREAD

**Issue by ChaT0n** [Prophet731/BFAdminCP#92]
Hello

I've noticed that in the site management -> server, changing the name of the server to display it in another way on the site doesn't work.
I tried to enter an entire sentence, or words seperated by comma, but nothing happens. It still shows the server name (from the configuration file) on the dashboard.

And also sometimes if I click on a server from the dashboard I get the following error message:
"Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists"
this error shows up like for a good moment like an hour (doesn't go if I refresh the page)
Thank you

**Comment by Prophet731** [comment]
This is a logic issue that's been fixed in the develop branch. You can easily fix it by opening up `app/bfacp/Battlefield/Server.php` in a text editor, preferably notepad++ if you don't have one yet. To fix it just replace the text `name_strip` with `filter`. As shown [here](https://github.com/Prophet731/BFAdminCP/blob/develop/app/bfacp/Battlefield/Server.php#L115). It will be located at line 115.
