### ISSUE TITLE
Wrong requirements.

### ISSUE THREAD

**Issue by CaptainSpleXx** [Prophet731/BFAdminCP#96]
If i run this under XAMPP its works fine. After i tried to install it onto my root-server, i had to install composer and had to change the composer file because the file was missing in "Patchwork\Utf8\Bootup". After this Laravel was only displaying emty sites until i enabled mod_rewrite.
Its take more then 2 Seconds to generate a site. Really disappointed in the installation process. So please for everyone who has problems, make a simple copy&paste tutorial. If someone does something there wrong doing it manually it can really simple f*ck up the whole webserver.
This CP looks nice but is slow and mostly useless, i personally stay with navicat.

**Comment by KyleDavis-IO** [comment]
CaptainSpleXx,

"If i run this under XAMPP its works fine. After i tried to install it onto my root-server, i had to install composer and had to change the composer file because the file was missing in "Patchwork\Utf8\Bootup". After this Laravel was only displaying emty sites until i enabled mod_rewrite."

This sounds like a server configuration and dependency problem on your end. Please remember that all server environments vary, it's up to the administrator to ensure that apache and PHP are set up correctly in order to run the framework. This is not a result stemming from the application development.

"Its take more then 2 Seconds to generate a site. Really disappointed in the installation process. So please for everyone who has problems, make a simple copy&paste tutorial. If someone does something there wrong doing it manually it can really simple f*ck up the whole webserver."

Could you please clarify this? It's challenging to extrapolate what you're saying.

"This CP looks nice but is slow and mostly useless, i personally stay with navicat."

Although I'm any user feedback is appreciated, please remember that this is an area for reporting issues.

After reading your statement here I can't determine if you are reporting an issue at all, or what it is that you would like for us to do with this information. Please consider retyping this issue. I'm recommending it be closed as unconstructive. Thank you for you submission.

**Comment by Prophet731** [comment]
@CaptainSpleXx 

Did you try to do the development branch? The install is pretty straightforward with the stable release.
