### ISSUE TITLE
REQUEST : server ip editing

### ISSUE THREAD

**Issue by ChaT0n** [Prophet731/BFAdminCP#98]
To be able to edit the server's ip, like this if we change the GSP we can just edit the ip without loosing eveything releated to chatlogs and stats

**Comment by Prophet731** [comment]
You can do this by just editing the `IP_Address` field in `tbl_server`. Just make sure you shutdown AdKats and the Stats logger before making this change. It's simply the game server ip with the RCON port at the end. I would rather not have an editor for this since everything in that table, except for a few columns, are updated by the plugin itself at a set interval.
